export { DashboardView } from "./dashboard-view"
export { ParticipantsView } from "./participants-view"
export { ProgrammesView } from "./programmes-view"
export { AnalyticsView } from "./analytics-view"
export { SettingsView } from "./settings-view"
